config/routes.rb
RealThematics::Application.routes.draw do

  resources :topics_users


  # Prevent user from visiting users page. Modified by Brandon. 2012/03/05.
  resources :users, :only => [:create, :new, :edit, :update, :invite]
  resources :topics, :only => [:create, :edit, :update, :show]
  resources :resources, :only => [:create, :edit, :update, :show]

  #
  get "signup/index"
  get "admin/index"
  
  get "signup" => "users#new"
  # 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
    get 'reset' => :reset
  end
  # 
  get 'admin' => 'admin#index'

  # Modified by Brandon. 2012/02/23.
  get "findtopics" => "find_topics#index", :as => 'find_topics'
  get "findtopics/search" => "find_topics#search", :as => 'search_topics'
  get "mytopics" => "my_topics#index", :as => 'my_topics'
  get "profile" => "user_profile#index", :as => 'user_profile'
  get "topicsboard" => "home_feeds#index", :as => 'home_feeds'
  get "search_url" => "home_feeds#search_url", :as => 'search_url'
  get "search_book" => "home_feeds#search_book", :as => 'search_book'

  get "invite" => "users#invite"
  get "users/reset" => "users#reset"
  get "update" => "users#edit"
  get "signin" => 'sessions#new'

  match "home_resources", :controller => "home_feeds", :action => "index"
  match "topic_resources_all", :controller => "topics", :action => "show"
  match "show_topic_status", :controller => "topics", :action => "show_topic_status"
  match "show_topic_links", :controller => "topics", :action => "show_topic_links"
  match "show_topic_videos", :controller => "topics", :action => "show_topic_videos"
  match "show_topic_books", :controller => "topics", :action => "show_topic_books"
  match "show_topic_mine", :controller => "topics", :action => "show_topic_mine"
  
  match "find_topics_list", :controller => "find_topics", :action => "index"
  match "my_topics_list", :controller => "my_topics", :action => "index"
  
  # Score counts
  match "score", :controller => "topics", :action => "score"
  match "resource_score", :controller => "resources", :action => "score"

  #root :to => 'home_feeds#index', :as => 'home_feeds'
  root :to => 'signup#index', :as => 'mainpage'

  # Redirect every error route to root. Added by Brandon. 2012/03/30
  match '*a', :to => 'errors#routing'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :presence=>true, :uniqueness=>true
  default_scope :order => 'created_at'
  # has_and_belongs_to_many :users
  has_many :topics_users
  has_many :topics_users_actions
  has_many :users, :through=>:topics_users
  has_many :resources
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  skip_before_filter :authorize, :only => [:index]

  @@topic_id = 1

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    
    @topic = Topic.find(params[:id])
    begin
      @relation = TopicsUser.find_by_topic_id_and_user_id params[:id], session[:user_id]
    rescue ActiveRecord::RecordNotFound
      puts "Relation not found"
      nil
    end
    begin
      # Fetch topic related resources
      #@resource_array = Resource.find_all_by_topic_id @topic.id
      @resource_array = Resource.paginate(
          :conditions => "topic_id = #{@topic.id}",
          :per_page => 20,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_all", :collection => @resource_array
        end
      }
      format.json { render json: @topic }
    end
  end

  # Split results in tab --- status
  def show_topic_status
    
    @topic = Topic.find(params[:id])
    begin
      # Fetch topic related resources
      #@resource_array = Resource.find_all_by_topic_id @topic.id
      @resource_array_status = Resource.paginate(
          :conditions => "topic_id = #{@topic.id} && type_id = 'status'",
          :per_page => 10,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_status", :collection => @resource_array_status
        end
      }
      format.json { render json: @topic }
    end
  end

  # Split results in tab --- links
  def show_topic_links
    
    @topic = Topic.find(params[:id])
    begin
      # Fetch topic related resources
      #@resource_array = Resource.find_all_by_topic_id @topic.id
      @resource_array_links = Resource.paginate(
          :conditions => "topic_id = #{@topic.id} && type_id = 'link'",
          :per_page => 10,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_links", :collection => @resource_array_links
        end
      }
      format.json { render json: @topic }
    end
  end

  # Split results in tab --- videos
  def show_topic_videos
    
    @topic = Topic.find(params[:id])
    begin
      # Fetch topic related resources
      #@resource_array = Resource.find_all_by_topic_id @topic.id
      @resource_array_videos = Resource.paginate(
          :conditions => "topic_id = #{@topic.id} && type_id = 'video'",
          :per_page => 10,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_videos", :collection => @resource_array_videos
        end
      }
      format.json { render json: @topic }
    end
  end

  # Split results in tab --- books
  def show_topic_books
    
    @topic = Topic.find(params[:id])
    begin
      # Fetch topic related resources
      @resource_array_books = Resource.paginate(
          :conditions => "topic_id = #{@topic.id} && type_id = 'book'",
          :per_page => 10,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end

    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_books", :collection => @resource_array_books
        end
      }
      format.json { render json: @topic }
    end
  end
  
  # Splic results in tab --- Mine
  def show_topic_mine
    
    @topic = Topic.find(params[:id])
    begin
      # Fetch topic related resources
      @resource_array_mine = Resource.paginate(
          :conditions => "topic_id = #{@topic.id} && user_id = #{session[:user_id]}",
          :per_page => 10,
          :page => params[:page],
          :order => 'up_count DESC, created_at DESC, add_count DESC, down_count ASC'
      )
    rescue ActiveRecord::RecordNotFound
      nil
    end
    
    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "topic_resources_all", :collection => @resource_array_mine
        end
      }
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    
    if (params[:keywordForAdd]!=nil && params[:keywordForAdd]!="")
      @topic.title = params[:keywordForAdd]
    end

    respond_to do |format|
      if @topic.save
        TopicsUser.create!(:topic_id=>@topic.id, :user_id=>session[:user_id])
        format.html { redirect_to @topic, notice: 'Topic was successfully created and added to your list.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
  
  def score    
    # Find topic by id
    begin
      @topic = Topic.find_by_id(params[:topic_id])
    rescue
      @topic = nil
    end
    
    # Find correspondent record in TopicResourceUser table based on user_id and topic_score_id.
    begin
      @topicscoreuser = TopicsUsersAction.find_or_create_by_user_id_and_topic_id(params[:user_id], params[:topic_id])
    rescue
      nil
    end
    
    if @topicscoreuser.user_action == 0
      if params[:user_action].to_i == 2 # User click on up
        @topicscoreuser.user_action = 2
        @topic.up_count += 1
      else # User click on down
        @topicscoreuser.user_action = 3
        @topic.down_count += 1
      end
      
      @topicscoreuser.save!
      @topic.save!
    end
    
    redirect_to :back
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
- form_for(@topic) do |f|
  - if @topic.errors.any?
    %div{:id => "error_explanation"}
      %h2= pluralize(@topic.errors.count, "error")
        prohibited this topic from being saved:
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg
  %div{:class => "field"}
    = f.label :title
    = f.text_field :title
  %div{:class => "field"}
    = f.label :description
    = f.text_area :description, :row => 6
  %div{:class => "actions"}
    = f.submit

app/views/topics/_topic_resources_all.html.haml
%p
=link_to topic_resources_all.user.screen_name,topic_resources_all.user 
="added a #{topic_resources_all.type_id} for"
=link_to topic_resources_all.topic.title, topic_resources_all.topic
="at"
%i= topic_resources_all.created_at
- if topic_resources_all.type_id == "status"
  %div{:id => "container", :class=>"row-fluid"}
    %p
      = topic_resources_all.title
    %br
    %a{:href => "#{resource_score_path(:resource_id => topic_resources_all.id, :user_id => session[:user_id], :user_action => 2)}"}
      %i.icon-arrow-up
    ="#{topic_resources_all.up_count}"

    %a{:href => "#{resource_score_path(:resource_id => topic_resources_all.id, :user_id => session[:user_id], :user_action => 3)}"}
      %i.icon-arrow-down
    ="#{topic_resources_all.down_count}"

    %span{:class => "label"}
      Added
      = topic_resources_all.add_count             
- else
  %div{:id => "container", :class=>"row-fluid"}
    %div{:class=>"span3"}
      %img{:src=>"#{topic_resources_all.image_uri}", :align=>"top", :alt=>"", :height=>"120",  "onerror"=>"this.src='/images/realthematics.png'"}
    %div{:class=>"span6"}
      - if topic_resources_all.type_id == "book"
        %b= topic_resources_all.title
        %p= link_to "Amazon Link", topic_resources_all.uri, :target => "_blank"
      - else
        %b= link_to topic_resources_all.title, topic_resources_all.uri, :target => "_blank"
        %p= topic_resources_all.description   
      %a{:href => "#{resource_score_path(:resource_id => topic_resources_all.id, :user_id => session[:user_id], :user_action => 2)}"}
        %i.icon-arrow-up
      ="#{topic_resources_all.up_count}"

      %a{:href => "#{resource_score_path(:resource_id => topic_resources_all.id, :user_id => session[:user_id], :user_action => 3)}"}
        %i.icon-arrow-down
      ="#{topic_resources_all.down_count}"

      %span{:class => "label"}
        Added
        = topic_resources_all.add_count  
%hr

app/views/topics/edit.html.haml
%h1
  Editing topic
= render 'form'
= link_to 'Show', @topic
= link_to 'Back', topics_path

app/views/topics/index.html.haml
%h2
  Find topics that interest you
%ul
  - @topics.each do |topic|
  %li= link_to topic.title, topic
%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1
  New topic
= render 'form'
= link_to 'Back', topics_path

app/views/topics/show.html.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:class => "active", :id => "real_topic_resource_all_tab"}
      %a{:href => "#real_topic_resource_all", "data-toggle" => "tab"}
        All
    %li{:id => "real_topic_resource_status_tab"}
      = link_to "Status", show_topic_status_path(:id => @topic.id)
    %li{:id => "real_topic_resource_links_tab"}
      = link_to "Links", show_topic_links_path(:id => @topic.id)
    %li{:id => "real_topic_resource_videos_tab"}
      = link_to "Videos", show_topic_videos_path(:id => @topic.id)
    %li{:id => "real_topic_resource_books_tab"}
      = link_to "Books", show_topic_books_path(:id => @topic.id)
    %li{:id => "real_topic_resource_mine_tab"}
      = link_to "Mine", show_topic_mine_path(:id => @topic.id)

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_all"}
      = render(:partial => "topic_resources_all", :collection => @resource_array)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array, :container => false)

    %div{:class => "tab-pane fade in active span10", :id => "real_topic_resource_status", :style => "display: none"}
    %div{:class => "tab-pane fade in active span10", :id => "real_topic_resource_links", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_videos", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_books", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_mine", :style => "display: none"}

app/views/topics/show_topic_books.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %p
    %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:id => "real_topic_resource_all_tab"}
      = link_to "All", @topic
    %li{:id => "real_topic_resource_status_tab"}
      = link_to "Status", show_topic_status_path(:id=>@topic.id)
    %li{:id => "real_topic_resource_links_tab"}
      = link_to "Links", show_topic_links_path(:id=>@topic.id)
    %li{:id => "real_topic_resource_videos_tab"}
      = link_to "Videos", show_topic_videos_path(:id=>@topic.id)
    %li{:class => "active", :id => "real_topic_resource_books_tab"}
      %a{:href => "#real_topic_resource_books", "data-toggle" => "tab"}
        Books
    %li{:id=>"real_topic_resource_mine_tab"}
      = link_to "Mine", show_topic_mine_path(:id=>@topic.id)

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_all", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_status", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_links", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_videos", :style => "display: none"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_books", :style => "display: block"}
      = render(:partial => "topic_resources_all", :collection => @resource_array_books)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array_books, :container => false)

app/views/topics/show_topic_links.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %p
    %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:id => "real_topic_resource_all_tab"}
      = link_to "All", @topic
    %li{:id => "real_topic_resource_status_tab"}
      = link_to "Status", show_topic_status_path(:id => @topic.id)
    %li{:class => "active", :id => "real_topic_resource_links_tab"}
      %a{:href => "#real_topic_resource_links", "data-toggle" => "tab"}
        Links
    %li{:id => "real_topic_resource_videos_tab"}
      = link_to "Videos", show_topic_videos_path(:id => @topic.id)
    %li{:id => "real_topic_resource_books_tab"}
      = link_to "Books", show_topic_books_path(:id => @topic.id)
    %li{:id=>"real_topic_resource_mine_tab"}
      = link_to "Mine", show_topic_mine_path(:id=>@topic.id)

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_all", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_status", :style => "display: none"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_links", :style => "display: block"}
      = render(:partial => "topic_resources_all", :collection => @resource_array_links)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array_links, :container => false)
    %div{:class => "tab-pane fade", :id => "real_topic_resource_videos", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_books", :style => "display: none"}

app/views/topics/show_topic_mine.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %p
    %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:id => "real_topic_resource_all_tab"}
      = link_to "All", @topic             
    %li{:id => "real_topic_resource_status_tab"}
      = link_to "Status", show_topic_status_path(:id => @topic.id)
    %li{:id => "real_topic_resource_links_tab"}
      = link_to "Links", show_topic_links_path(:id => @topic.id)
    %li{:id => "real_topic_resource_videos_tab"}
      = link_to "Videos", show_topic_videos_path(:id => @topic.id)
    %li{:id => "real_topic_resource_books_tab"}
      = link_to "Books", show_topic_books_path(:id => @topic.id)
    %li{:class => "active", :id => "real_topic_resource_mine_tab"}
      %a{:href => "#real_topic_resource_mine", "data-toggle" => "tab"}
        Mine

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_all", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_status", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_links", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_videos", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_books", :style => "display: none"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_mine", :style => "display: block"}
      = render(:partial => "topic_resources_all", :collection => @resource_array_mine)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array_mine, :container => false)

app/views/topics/show_topic_status.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %p
    %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:id => "real_topic_resource_all_tab"}
      = link_to "All", @topic
    %li{:class => "active", :id => "real_topic_resource_status_tab"}
      %a{:href => "#real_topic_resource_status", "data-toggle" => "tab"}
        Status
    %li{:id => "real_topic_resource_links_tab"}
      = link_to "Links", show_topic_links_path(:id => @topic.id)
    %li{:id => "real_topic_resource_videos_tab"}
      = link_to "Videos", show_topic_videos_path(:id => @topic.id)
    %li{:id => "real_topic_resource_books_tab"}
      = link_to "Books", show_topic_books_path(:id => @topic.id)
    %li{:id=>"real_topic_resource_mine_tab"}
      = link_to "Mine", show_topic_mine_path(:id=>@topic.id)

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_all", :style => "display: none"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_status", :style => "display: block"}
      = render(:partial => "topic_resources_all", :collection => @resource_array_status)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array_status, :container => false)
    %div{:class => "tab-pane fade", :id => "real_topic_resource_links", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_videos", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_books", :style => "display: none"}

app/views/topics/show_topic_videos.haml
%link{:rel => "stylesheet", :href => "/stylesheets/topics.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
.notice_alert
  - if notice
    %p{:id=>"notice", :class=>"span5 alert alert-success"}
      = notice
      %a{:class=>"close", "data-dismiss"=>"alert"}
        ×
= render 'share_form'
.span10#real_topic_info
  %p
    %h2= @topic.title
  %p
    = @topic.description
  %br
  -# Resources contained by topic
  %ul{:id => "tab", :class => "nav nav-tabs"}
    %li{:id => "real_topic_resource_all_tab"}
      = link_to "All", @topic
    %li{:id => "real_topic_resource_status_tab"}
      = link_to "Status", show_topic_status_path(:id => @topic.id)
    %li{:id => "real_topic_resource_links_tab"}
      = link_to "Links", show_topic_links_path(:id => @topic.id)
    %li{:class => "active", :id => "real_topic_resource_videos_tab"}
      %a{:href => "#real_topic_resource_videos", "data-toggle" => "tab"}
        Videos
    %li{:id => "real_topic_resource_books_tab"}
      = link_to "Books", show_topic_books_path(:id => @topic.id)
    %li{:id=>"real_topic_resource_mine_tab"}
      = link_to "Mine", show_topic_mine_path(:id=>@topic.id)

  %div{:id => "real_topic_content", :class => "tab-content"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_all", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_status", :style => "display: none"}
    %div{:class => "tab-pane fade", :id => "real_topic_resource_links", :style => "display: none"}
    %div{:class => "tab-pane fade in active span9", :id => "real_topic_resource_videos", :style => "display: block"}
      = render(:partial => "topic_resources_all", :collection => @resource_array_videos)
    %div{:class => "span5"}
      %div{:class => "flickr_pagination"}
        = will_paginate(@resource_array_videos, :container => false)
    %div{:class => "tab-pane fade", :id => "real_topic_resource_books", :style => "display: none"}