config/routes.rb
RealThematics::Application.routes.draw do

  resources :topics_users


  # Prevent user from visiting users page. Modified by Brandon. 2012/03/05.
  resources :users, :only => [:create, :new, :edit, :update, :invite]
  resources :topics, :only => [:create, :edit, :update, :show]
  resources :resources, :only => [:create, :edit, :update, :show]

  #
  get "signup/index"
  get "admin/index"
  
  get "signup" => "users#new"
  # 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
    get 'reset' => :reset
  end
  # 
  get 'admin' => 'admin#index'

  # Modified by Brandon. 2012/02/23.
  get "findtopics" => "find_topics#index", :as => 'find_topics'
  get "findtopics/search" => "find_topics#search", :as => 'search_topics'
  get "mytopics" => "my_topics#index", :as => 'my_topics'
  get "profile" => "user_profile#index", :as => 'user_profile'
  get "topicsboard" => "home_feeds#index", :as => 'home_feeds'
  get "search_url" => "home_feeds#search_url", :as => 'search_url'
  get "search_book" => "home_feeds#search_book", :as => 'search_book'

  get "invite" => "users#invite"
  get "users/reset" => "users#reset"
  get "update" => "users#edit"
  get "signin" => 'sessions#new'

  match "home_resources", :controller => "home_feeds", :action => "index"
  match "topic_resources_all", :controller => "topics", :action => "show"
  match "show_topic_status", :controller => "topics", :action => "show_topic_status"
  match "show_topic_links", :controller => "topics", :action => "show_topic_links"
  match "show_topic_videos", :controller => "topics", :action => "show_topic_videos"
  match "show_topic_books", :controller => "topics", :action => "show_topic_books"
  match "show_topic_mine", :controller => "topics", :action => "show_topic_mine"
  
  match "find_topics_list", :controller => "find_topics", :action => "index"
  match "my_topics_list", :controller => "my_topics", :action => "index"
  
  # Score counts
  match "score", :controller => "topics", :action => "score"
  match "resource_score", :controller => "resources", :action => "score"

  #root :to => 'home_feeds#index', :as => 'home_feeds'
  root :to => 'signup#index', :as => 'mainpage'

  # Redirect every error route to root. Added by Brandon. 2012/03/30
  match '*a', :to => 'errors#routing'
end

app/controllers/find_topics_controller.rb
class FindTopicsController < ApplicationController
 # skip_before_filter :authorize
  def index
    #@topics = Topic.where("title like ?", "%#{params[:keyword]}%")
    begin
      # Fetch topic related resources
      if(params[:keyword] != nil)
        @topics = Topic.paginate(
            :conditions => ["title LIKE ?", params[:keyword] + '%'],
            :per_page => 30,
            :page => params[:page]
        )
      else
        @topics = Topic.paginate(
            :per_page => 30,
            :page => params[:page]
        )
      end
    rescue ActiveRecord::RecordNotFound
      nil
    end
    
    @topic = Topic.new
    respond_to do |format|
      format.html {
        if request.xhr?
          render :partial => "find_topics_list", :collection => @topics
        end
      }
      format.js
      format.json { render json: @topics }
    end
  end

  def is_topic_in_my_list?(topic)
    TopicsUser.where("topic_id = ? and user_id = ?", topic.id, session[:user_id]).empty? ? false : true
  end
end

app/helpers/find_topics_helper.rb
module FindTopicsHelper
end

app/views/find_topics/_find_topics_list.haml
%hr
.row-fluid#new_feeds
	%h3 
		= link_to find_topics_list.title, find_topics_list
	%p	
		= find_topics_list.description
	- if @_controller.is_topic_in_my_list?(find_topics_list)
		%i I already added this.
	-else
		= button_to 'Add to my topics', topics_users_path(:topic_id => find_topics_list.id, :user_id => session[:user_id]), :class => "btn btn-mini btn-success"
	%a{:href => "#{score_path(:user_action => 2, :topic_id => find_topics_list.id, :user_id => session[:user_id])}"}
		%i.icon-arrow-up
	="#{find_topics_list.up_count}"

	%a{:href => "#{score_path(:user_action => 3, :topic_id => find_topics_list.id, :user_id => session[:user_id])}"}
		%i.icon-arrow-down
	="#{find_topics_list.down_count}"



	

app/views/find_topics/_form.html.haml
- if flash[:alert]
	%p{:id => "notice"}
		= flash[:alert]
= form_tag find_topics_url, :method => "get" do
	%div{:class => "well span10", :id => "search_topics"}
		= text_field_tag :keyword, params[:keyword], :class => "span8", :style => "margin: 0 2%; height: 30px", "placeholder" => "Search topics ...", :id => "real_search_field"
		&nbsp &nbsp 
		%button{:class => "btn btn-large btn-primary", :onclick => "return checkKeyword();"}
			Search

%script{:type => "text/javascript"}
	:plain
		function checkKeyword(){
			var v = document.getElementById ("real_search_field");
			if (v.value=="") {
				return false;
			}else{
				return true;
			}
		}

app/views/find_topics/index.html.haml
%link{:rel => "stylesheet", :href => "/stylesheets/pagination.css"}
:css
	.button_to div {display: inline;}
	.button_to {display: inline;}

.notice_alert
	- if notice
		%p{:id=>"notice", :class=>"span5 alert alert-success"}
			= notice
			%a{:class=>"close", "data-dismiss"=>"alert"}
				×
= render 'form'
.span10#search_results
	-if (params[:keyword]=="" || params[:keyword]==nil)
		%h2
			%b Topics that you may interest in.
		#recommend_topic If you want to check on a specific topic, use the search above.
	-else
		%h2
			#recommend_topic Not the topic you want? Add new topic to Real Thematics.
			%br
			= form_tag :controller => "topics", :action => "create", :method => "post" do
				= text_field_tag :keywordForAdd, params[:keyword], "style"=>"display:none"
				%button{:class => "btn btn-large btn-primary"} 
					Add 
					%strong
						#{params[:keyword]} 
					to Real Thematics!
.span10#whole_page
	= render(:partial => "find_topics_list", :collection => @topics)
	%hr
	%div{:class => "span3"}
		%div{:class => "flickr_pagination"}
			= will_paginate(@topics)
= render "wigets/joyride_find_topics"

app/views/find_topics/search.html.haml
%table{:class => "table-bordered"}
  %thead
  %tbody
    %tr
      %td
        Hello, world