config/routes.rb
RealThematics::Application.routes.draw do

  resources :topics_users


  # Prevent user from visiting users page. Modified by Brandon. 2012/03/05.
  resources :users, :only => [:create, :new, :edit, :update, :invite]
  resources :topics, :only => [:create, :edit, :update, :show]
  resources :resources, :only => [:create, :edit, :update, :show]

  #
  get "signup/index"
  get "admin/index"
  
  get "signup" => "users#new"
  # 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
    get 'reset' => :reset
  end
  # 
  get 'admin' => 'admin#index'

  # Modified by Brandon. 2012/02/23.
  get "findtopics" => "find_topics#index", :as => 'find_topics'
  get "findtopics/search" => "find_topics#search", :as => 'search_topics'
  get "mytopics" => "my_topics#index", :as => 'my_topics'
  get "profile" => "user_profile#index", :as => 'user_profile'
  get "topicsboard" => "home_feeds#index", :as => 'home_feeds'
  get "search_url" => "home_feeds#search_url", :as => 'search_url'
  get "search_book" => "home_feeds#search_book", :as => 'search_book'

  get "invite" => "users#invite"
  get "users/reset" => "users#reset"
  get "update" => "users#edit"
  get "signin" => 'sessions#new'

  match "home_resources", :controller => "home_feeds", :action => "index"
  match "topic_resources_all", :controller => "topics", :action => "show"
  match "show_topic_status", :controller => "topics", :action => "show_topic_status"
  match "show_topic_links", :controller => "topics", :action => "show_topic_links"
  match "show_topic_videos", :controller => "topics", :action => "show_topic_videos"
  match "show_topic_books", :controller => "topics", :action => "show_topic_books"
  match "show_topic_mine", :controller => "topics", :action => "show_topic_mine"
  
  match "find_topics_list", :controller => "find_topics", :action => "index"
  match "my_topics_list", :controller => "my_topics", :action => "index"
  
  # Score counts
  match "score", :controller => "topics", :action => "score"
  match "resource_score", :controller => "resources", :action => "score"

  #root :to => 'home_feeds#index', :as => 'home_feeds'
  root :to => 'signup#index', :as => 'mainpage'

  # Redirect every error route to root. Added by Brandon. 2012/03/30
  match '*a', :to => 'errors#routing'
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  #default_scope :order => 'created_at DESC, up_count DESC, add_count DESC, down_count ASC'
  belongs_to :users
  belongs_to :topics
  has_many   :resources_users_actions
  
  def topic
    Topic.find(self.topic_id)
    rescue ActiveRecord::RecordNotFound
      Topic.new
  end
  def user
    aUser = User.find(self.user_id)
    if aUser.screen_name==nil
      aUser.screen_name = "a user"
    end
    aUser
    rescue ActiveRecord::RecordNotFound
      User.new
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :presence=>true, :uniqueness=>true
  default_scope :order => 'created_at'
  # has_and_belongs_to_many :users
  has_many :topics_users
  has_many :topics_users_actions
  has_many :users, :through=>:topics_users
  has_many :resources
end

app/models/topics_user.rb
class TopicsUser < ActiveRecord::Base
  validates :topic_id, :uniqueness => { :scope => :user_id,
      :message => "It's already in your list" }
  belongs_to :users
  belongs_to :topics
  
  def topicTitle
    Topic.find(self.topic_id).title
  end
end

app/models/topics_users_action.rb
class TopicsUsersAction < ActiveRecord::Base
  before_save :default_values
  validate :allow_nil => true, :presence => true, :uniqueness => true
  belongs_to :users
  
  def default_values
    self.user_action ||= 0  # 0 - none, 1 - add, 2 - up, 3 - down
  end
  
end

app/models/user.rb
require 'digest/sha2'
class User < ActiveRecord::Base
  validates     :email, :presence => true, :uniqueness => true
  validates_format_of :email,:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  attr_reader   :password
  validate      :password_must_be_present
  has_many      :topics_users
  has_many      :topics, :through=>:topics_users
  has_many      :resources
  has_many      :topics_users_actions
  has_many      :resources_users_actions

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "mocha" + salt)
  end
  
  def User.authenticate(email, password)
    if user = find_by_email(email)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end
  
  def password=(password)
    @password = password
    if password.present?
        generate_salt
        self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  private
    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end

    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Pageless function.
  def pageless(total_pages, url=nil, host=nil, container=nil)
    
    opts = {
        :totalPages => total_pages,
        :url        => url,
        :loaderMsg  => 'Loading more resources',
    }

    container && opts[:container] ||= container

    javascript_tag("$('##{host}').pageless(#{opts.to_json});")
  end

  # Pageless function - self-defined.
  def pageless_topics(total_pages, url=nil, element=nil, container=nil)
    
    opts = {
        :totalPages => total_pages,
        :url        => url,
        :loaderMsg  => 'Loading more resources',
    }

    element && opts[:element] ||= element
    container && opts[:container] ||= container

    javascript_tag("$('#real_topic_content').pageless_brandon(#{opts.to_json});")
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/find_topics_helper.rb
module FindTopicsHelper
end

app/helpers/home_feeds_helper.rb
module HomeFeedsHelper
end

app/helpers/my_topics_helper.rb
module MyTopicsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/topic_scores_helper.rb
module TopicScoresHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/topics_users_helper.rb
module TopicsUsersHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.haml
%h1
  Admin#index
%p
  Find me in app/views/admin/index.html.erb

app/views/notifier/registration_succeed.text.erb
Dear <%= @user.email %>:

Congratulations!
Your registration has been confirmed.
And thank you for your interest in Real Thematics.

We hope you will have a enjoyable trip with Real Thematics.

Enjoy and have fun! Let's make every sharing online meaningful!

Best Regards,
The Real Thematics Team

app/views/notifier/reset_password.text.erb
Dear <%= @user.email %>:

We received your request about forgetting your password. Below is the link for create a new password of you account.

http://realthematics.com/users/reset?email=<%=@user.email%>&hash=<%= @user.hashed_password%>


We hope you will have a enjoyable trip with Real Thematics.

Enjoy and have fun! Let's make every sharing online meaningful!

Best Regards,
The Real Thematics Team

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topics_user_id %><br />
    <%= f.number_field :topics_user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Title</th>
    <th>Type</th>
    <th>Uri</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.description %></td>
    <td><%= resource.title %></td>
    <td><%= resource.type_id %></td>
    <td><%= resource.uri %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @resource.topics_user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @resource.description %>
</p>

<p>
  <b>Title:</b>
  <%= @resource.title %>
</p>

<p>
  <b>Type:</b>
  <%= @resource.type_id %>
</p>

<p>
  <b>Uri:</b>
  <%= @resource.uri %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/shared/_back_to_top.haml
%a
  %div{:id=>"toplink", :style=>"opacity: 1;"}
    %img{:src=>"/images/back-to-top.png", :align=>"center"}

app/views/shared/_css_application.haml
-#= stylesheet_link_tag "application", :media => "all"
%link{:rel => "stylesheet", :href => "/stylesheets/bootstrap.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/bootstrap-responsive.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/application.css"}
%link{:rel => "stylesheet", :href => "/stylesheets/joyride-1.0.3.css"}

app/views/shared/_footer.haml
%footer
  %hr
  %span{:class => "span2"}
    %p
      &copy; Real Thematics 2012
  %div{:class => "span1", :id=>"real_twitter_share"}
    %a(href="https://twitter.com/share" class="twitter-share-button" data-url="http://realthematics.com" data-via="realthematics" data-hashtags="realthematics")Tweet
  %div{:class => "span2", :id=>"real_facebook_share"}
    .fb-like(data-href="http://realthematics.com" data-send="false" data-width="450" data-show-faces="false" data-font="verdana")
  %script{:type => "text/javascript"}
    :plain
      !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/shared/_js_application.haml
= javascript_include_tag 'application'
%script{:type => "text/javascript", :src => "/js/bootstrap-transition.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-alert.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-dropdown.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-modal.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-scrollspy.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-tab.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-tooltip.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-popover.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-button.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-collapse.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-carousel.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/bootstrap-typeahead.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/real_go_top.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/jquery.joyride-1.0.3.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/hoveredit.jquery.min.js", :charset => "utf-8"}
%script{:type => "text/javascript", :src => "/js/autoresize.jquery.min.js", :charset => "utf-8"}

%script(src="//html5shim.googlecode.com/svn/trunk/html5.js")

app/views/shared/_menu.haml
%div{:class => "navbar navbar-fixed-top"}
  %div{:class => "navbar-inner"}
    %div{:class => "container-fluid"}
      = link_to "Real Thematics", home_feeds_path, :class=>"brand"
      - if session[:user_id]          
        %ul.nav
          %li{:class =>"#{'active' if params[:controller] == 'find_topics' }" }
            = link_to "Find Topics", find_topics_path, :class => "navbar-text"
          %li{:class =>"#{'active' if params[:controller] == 'my_topics' }" }
            = link_to "My Topics", my_topics_path, :class => "navbar-text"

        %ul{:class => "nav pull-right"}
          %li{:class => "dropdown #{'active' if params[:controller] == 'users' }"}
            %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
              = "#{session[:screen_name]}"
              %b{:class => "caret"}
            %ul{:class => "dropdown-menu"}
              %li
                = link_to "Setting", "/users/#{session[:user_id]}/edit"
                = link_to 'Sign out', logout_path, :method => :delete
      - else
        %ul.nav.pull-right
          %li{:class =>"#{'active' if params[:controller] == 'users' }" }
            = link_to "Sign up", signup_path, :class => "navbar-text"
          %li{:class =>"#{'active' if params[:controller] == 'sessions' }" }
            = link_to "Sign in", login_path, :class => "navbar-text"
          %li
            = link_to "Blog", "http://realthematics.com/blog", :class => "navbar-text", :target => "_blank"

app/views/shared/_meta_application.haml
= csrf_meta_tags
%meta(charset="utf-8")
%title= "Real Thematics - Share your topics"
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%meta(name="description" content="Find and share useful resources socially and more effectively")
%meta(name="author" content="The Real Team")